### ISSUE TITLE
Wrong style for folded editor regions

### ISSUE THREAD

**Issue by arcticicestudio** [microsoft/theme-converter-for-vs#107]
Folded regions in the editor using a foreground and border color that is not part of the currently active theme.
My suggestions is that such elements are highlighted like comments to not take the focus off the code and improve the consistent code appearance.

<p align="center"><strong>Folded code regions with "Nord" set as active VS theme.</strong></p>
<p align="center"><img src="https://user-images.githubusercontent.com/7836623/132989460-da2c2461-526e-4bc6-8ebb-1c174232f66f.png"></p>

#### Reproduction Steps

1. Set Nord as active theme.
2. Close any region within the code editor and validate that the foreground and border color of the fold does not match the currently active theme.

#### Expected Behavior

I expected that the code folds are highlighted like comments to not take the focus off the code and improve the consistent code appearance.

#### Environment

**Converter version**: commit 34bbde361cb3511f7b6ae99dd2689c1825cca60e
**VS version**: `17.0.0 Preview 3`
**Theme(s) used**: [Nord][1]

#### (Possible) Release Impact

This issue is kind of a low annoyance because it is only visible when using code foldings so this can be improved in a future version and it not a blocker for a theme release.

[1]: https://marketplace.visualstudio.com/items?itemName=arcticicestudio.nord-visual-studio-code

**Comment by ketttY** [comment]
Hi @arcticicestudio, thank you again for your feedback. With the latest change, the collapsed area is now using the same color as the region name. Please note that the collapsed text color is only read at VS start up, therefore, in order to see this change, you will need to first open VS with the new theme patched, select your target theme, and then restart VS.
Attached is the comparison.
Before:
![image](https://user-images.githubusercontent.com/34032260/134599332-230f74b6-91cf-4671-b8cc-c13514643e88.png)
After: 
![image](https://user-images.githubusercontent.com/34032260/134599349-3b4eed3f-d233-4ed5-9e4f-a17947b79bfb.png)
Unfolded:
![image](https://user-images.githubusercontent.com/34032260/134599361-e5257bc8-fcd8-4460-b236-1c99e5fc6963.png)
VS Code folded:
![image](https://user-images.githubusercontent.com/34032260/134600400-33c72fcb-011a-450e-82d4-26957613ff56.png)

**Comment by arcticicestudio** [comment]
Thanks for the quick fix, works like expected. This also revealed that there are some TextMate scopes missing in Nord for VS Code to style regions in order to style them like comments 😄
