### ISSUE TITLE
Semantic Tokens?

### ISSUE THREAD

**Issue by AkJardo** [microsoft/theme-converter-for-vs#132]
Hi, I think the conversion doen't work properly. For this Token
![image](https://user-images.githubusercontent.com/5805609/142754005-42f41d5b-c7df-4aef-bf2c-c28e34fa8f44.png)

Comparision between VS Code and VS 2022
![image](https://user-images.githubusercontent.com/5805609/142754042-73412030-a903-4090-8283-d4ada0449911.png)
![image](https://user-images.githubusercontent.com/5805609/142754060-43053285-b701-46be-afb2-59e5d7659e60.png)

Attached json theme
[cobalt2.txt](https://github.com/microsoft/theme-converter-for-vs/files/7575899/cobalt2.txt)

**Comment by ketttY** [comment]
Hi @AkJardo, thank you for your feedback. This is caused by the different granularities that VS Code and VS provide when colorizing the editor tokens. For example, for the code below:
```
public class A
{
    public async B Method()
    {
    }
}
```
In VS Code, the colorization is:
A: entity.name.type.class.cs
B: storage.type.cs

In VS:
A, B: class name

In the mapping for this tool, we chose to map from `entity.name.type.class.cs` to `class name` ([here](https://github.com/microsoft/theme-converter-for-vs/blob/bbb9f073b1535e20e82e3322900c0af6e4029ad4/ThemeConverter/ThemeConverter/TokenMappings.json#L117)) because we have observed a higher quality with this mapping during experimentation. However, in some cases, like the one you are seeing, the other one might be better. If you want to change this token for your theme, you can feel free to change the mapping at the line mentioned above and convert again, or you can change the `class name` token to any color using extensions like [Carnation2022](https://marketplace.visualstudio.com/items?itemName=ryzngard.Carnation2022020) (editor focused) or [Visual Studio Color Theme Designer 2022](https://marketplace.visualstudio.com/items?itemName=idex.colorthemedesigner2022) (shell and editor).

The other thing to notice is that when `entity.name.type.class.cs` is not defined in the VS Code theme, we will fall back to use the `storage.type.cs` color for VS' `class name` ([here](https://github.com/microsoft/theme-converter-for-vs/blob/bbb9f073b1535e20e82e3322900c0af6e4029ad4/ThemeConverter/ThemeConverter/VSCTokenFallback.json#L5))

Please let me know if you have any additional questions. Thank you!

**Comment by AkJardo** [comment]
Thank you @ketttY!! I will try editing the line you told me and generate the theme again.

**Comment by vllirette** [comment]
@AkJardo If ever you make it work, I would be interested to know how you did it! I have a similar issue with converting my theme.

**Comment by AkJardo** [comment]
@vllirette point is that you can't dissociate the two items, in VSCode that color ("Task") is for storage.type.cs, and that color is not mapped to VSStudio "class name", instead "class name" came from entity.name.type.class.cs. But you can change this mapping cloning the repo and building the tool. You can check this with the Carnation extension. Also it would be awesome to allow cursive in VSStudio hahaha.
