### ISSUE TITLE
Text in 'Git Changes' warning/error panel is not readable

### ISSUE THREAD

**Issue by DirkDeclercq** [microsoft/theme-converter-for-vs#133]
When using the converter-tool with my included VS-code settings (inside zip), the 'Git Changes' waning/error panel was not readable.

![image](https://user-images.githubusercontent.com/25179893/146177482-2dc0ab50-6eba-4712-baad-450bb2a77ea9.png)
(remark: screenshot is taken, after I have fixed the tags - don't remember anymore which tags I have changed with the 'Visual Studio Color Theme Designer 2022)

**Environment (please complete the following information):**
 - Converter version: 
 Commit bbb9f073b1535e20e82e3322900c0af6e4029ad4
Author: Keting Yang <ketyang@microsoft.com>
Date: maandag 25 oktober 2021 18:35
Parent: a02c1e0e

 - VS version: 17.0.3

[VSCode-ThemeSettings.zip](https://github.com/microsoft/theme-converter-for-vs/files/7718903/VSCode-ThemeSettings.zip)

**Comment by huguesv** [comment]
Hi Dirk, I've converted your attached theme using the latest version of the converter (same as you) and the info bar is readable. There's also some other visual differences from your screenshot, I don't know if those are due to manual changes you've made using the theme designer.

![image](https://user-images.githubusercontent.com/1696845/146240055-57b1e87d-f50e-4470-b512-86280d5b7a62.png)

**Comment by DirkDeclercq** [comment]
Ok, sorry then for the inconvenience.
It must have to do with the manual changes I've made.
