### ISSUE TITLE
Some conversion bugs

### ISSUE THREAD

**Issue by fisheva** [microsoft/theme-converter-for-vs#140]
Hi, here are some bugs I met when I used theme-converter-for-vs to update Eva Theme for VS. These following API I mentioned are all properties in "Colors" of Eva Theme generated json file. I will describe each bug in a paragraph.
![企业微信截图_20220218144900](https://user-images.githubusercontent.com/17448419/154632343-f4269f6d-e23f-4979-95c2-ddb1cf683902.png)

These bugs have some same Reproduce Steps and Environment. So I write down here first.

**Environment (please complete the following information):**
 - Converter version: After ketttY 97th commit at Jan 8 (I didn't found the version number).
 - VS version: [Professional 2022 (64-bit) , 17.0.4]
 - Theme used: [[Eva Theme](https://marketplace.visualstudio.com/items?itemName=fisheva.eva-theme)]

**To Reproduce**
1，Git clone this [repository](https://github.com/fisheva/Eva-Theme-for-VS-for-issue-of-theme-converter-for-vs). `git clone git@github.com:fisheva/Eva-Theme-for-VS-for-issue-of-theme-converter-for-vs.git`
2，After clone repository above, install Eva Theme for VS by 2022.visx file.
3，Open Eva Theme converter project, double-click 2022.sln(2022/VISX Project/2022.sln) file.
4，In Eva Theme converter project, double-click source.extention.vsixmanifest file.

**Additional context**
The Eva Theme for VS in the repository above is a version used for testing. If you want to experience the official version of Eva Theme for VS, please visit [here](https://marketplace.visualstudio.com/items?itemName=fisheva.eva-theme-vs).

**Comment by fisheva** [comment]
**Bug 1:**

**Describe the bug**
"dropdown.background" also affects all background colors in the selection box. See the screenshots below for comparion. The selection background and current select option background in the Eva Light (added "dropdown.background": "#f1f4fb") are all the same. Make the selected texts hard to read.

**Screenshots**
Use Visual Studio default Light theme, screenshot.
![企业微信截图_20220119152818](https://user-images.githubusercontent.com/17448419/150086399-7e2103e8-c035-4e3c-af01-be0ecb252e3a.png)

Use Eva Light, screenshot.
![企业微信截图_20220216155203](https://user-images.githubusercontent.com/17448419/154224694-94aae896-3992-43f0-9a6e-f693878c9ae5.png)

**To Reproduce**
Steps to reproduce the behavior (after the reproduce steps of paragraph 1):
5，Switch the theme to Eva Light.
6，Click "Assets" → "Edit" → drop down selection box.

**Expected behavior**
The selection background and current select option background affects by "list.activeSelectionBackground" instead of "dropdown.background".

**Impact**
Because of this bug, I have removed "dropdown.background" option in the currently release of the official version of the conversion JSON, the area it affects currently displays the default theme colors.

**Additional context**
If after the repair, the selection background and current select option background is not affected by "list.activeSelectionBackground", please tell me which API it is. Thanks!

**Comment by fisheva** [comment]
**Bug 3:**

**Describe the bug**
The independently window title color is black both in Eva Dark and Eva Light. And I find no  API can affect it's color. When the code window is displayed independently, the color of the title bar is hard to read in Eva Dark.

**Screenshots**
Use Visual Studio default Dark theme, screenshot.
![企业微信截图_20220218100640](https://user-images.githubusercontent.com/17448419/154609813-754024af-a1c7-483b-9c17-f49bf4cbe66b.png)

Use Eva Dark, screenshot. The independently window title is hard to read.
![企业微信截图_20220218100600](https://user-images.githubusercontent.com/17448419/154609826-516b5aba-8c26-4e69-8241-b86eb7aa5c3e.png)

Use Eva Test, screenshot. The independently window title color is still black.
(Eva Test is a theme I used to initially find the scope of the API. All APIs are set, but none of them are set to black.)
![企业微信截图_20220218104731](https://user-images.githubusercontent.com/17448419/154609837-90feb73f-9816-4882-8068-46e512ea72c2.png)

**To Reproduce**
Steps to reproduce the behavior (after the reproduce steps of paragraph 1):
5，Switch the theme to Eva Dark.
6，Drag and drop 'AssemblyInfo.cs' file to a independently window.

**Expected behavior**
The independently window title color is controlled by a generate JSON API.

**Impact**
This bug is reported by an Eva Theme user in issue.

**Additional context**
After the repair, please tell me which API it is. Thanks!

**Comment by ketttY** [comment]
Hi @fisheva, thank you for your feedback! We will look into these issues soon and let you know once the fix is merged!

**Comment by ketttY** [comment]
Hi @fisheva, for bug 2, I checked VS Code's behavior and seems like the status bar is not changing color during building and I think it might make sense for the converted theme to match VS Code's for better parity? Wondering what do you think?
!<img width="617" alt="image" src="https://user-images.githubusercontent.com/34032260/157566270-75da3cfd-3426-4574-ae44-55eff9121009.png">
![image](https://user-images.githubusercontent.com/34032260/157566275-266f199c-8324-42c8-81f5-b946feac62d0.png)

For bug 1, 3 and 4, the fix is in #141. 
The vs code API that controls the floating window title text is `titleBar.activeForeground` when the window has focus and `titleBar.inactiveForeground` when the window doesn't have focus. 
For both text selection issues, the corresponding VS Code API is `selection.background`.

Feel free to check if the fix matches your expectation and let me know if you have any questions! Thank you!

**Comment by ketttY** [comment]
Closing this bug as #141 is merged. If the fix did not meet your expectations, feel free to reactivate this bug. Thanks again for your feedback!

**Comment by fisheva** [comment]
Hi, @ketty! Very sorry for reply late, I have a lot of development tasks these days, only have time to deal with Eva Theme things on weekends. 

I have a different opinion on the status bar color bug. Although Eva Theme for VS is converted from Eva Theme for VSCode, since the current service platform is Visual Studio, it should conform to the user habits of Visual Studio platform. Since the default  Visual Studio theme status bar changes color during building, other themes are best to keep this feedback, just in a different color style. So I think there needs an option to set the staus bar color during building.

I pulled the latest code of theme-converter-for-vs today and want to update Eva Theme for VS. But I find that my Visual Studio license had expired... 
![企业微信截图_20220312201144](https://user-images.githubusercontent.com/17448419/158019274-35bbf01f-7592-4e3a-b267-4df5c87b9a8c.png)
![企业微信截图_20220312202631](https://user-images.githubusercontent.com/17448419/158019281-339f12e0-4b45-4494-a8a8-bb4b58858f3f.png)
I usually use VSCode for development, and use Visual Studio just to test Eva Theme for VS. Can I apply for an available license for both 2019 and 2022 ? (Some Eva Theme users still use VS2019). I appreciate for it!

The last question, a user left a bug report under my Eva Theme for VS Marketplace. I don't know how to deal with it and reply. Is this a bug caused by the conversion process?
![企业微信截图_20220312211936](https://user-images.githubusercontent.com/17448419/158019506-a2764536-b9a5-444c-89d9-8eef04d665bb.png)

**Comment by ketttY** [comment]
Hi @fisheva, thank you for your reply!
- For the status bar, in a long term, we will consider making a list of tunable controls for this kind of scenarios, so that users can have better control over the result. For now, I have made this branch: [dev/ketyang/buildingstatusbar](https://github.com/microsoft/theme-converter-for-vs/tree/dev/ketyang/buildingstatusbar) for the behavior that you are looking for:  `statusBar.debuggingBackground/foreground` will control both debugging and building status bar colors in VS. Therefore, if you want, feel free to use that branch as an alternative. 
- The "VS.Cider.ComboBoxColor" issue that the user mentioned should be fixed by reconverting the theme with the latest converter.
- From what I know, @gracegtaylor is now looking at the license issue, so she might be able to provide more information on that.

**Comment by fisheva** [comment]
Hi @ketty, very thanks for solving my issues perfectly！
